POST http://localhost:3000/api/category
Content-Type: application/json

{
    "title": "Category 1",
    "description": "Category 1 description"
}

###

POST http://localhost:3000/api/category
Content-Type: application/json

{
    "title": "Category 2",
    "description": "Category 2 description"
}

###

GET http://localhost:3000/api/category

###

PUT http://localhost:3000/api/category/669624d5d70d9339115b07f1
Content-Type: application/json

{
    "title": "Category 1 updated",
    "description": "Category 1 description updated"
}

###

DELETE http://localhost:3000/api/category/669624d5d70d9339115b07f1